// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace XUtility
{
    /// <summary>
    /// Curve.
    /// </summary>
    public class Curve
    {
        /// <summary>
        /// Gets the shape.
        /// </summary>
        /// <value>The shape.</value>
        public ShapeType Shape { get; private set;}

        private Vector3[] points;

        private float[] distances;

        /// <summary>
        /// Gets the point.
        /// </summary>
        /// <returns>The point.</returns>
        /// <param name="t">T.</param>
        public Vector3 GetPoint(float t)
        {
            if (points == null)
                return Vector3.zero;

            t = Mathf.Clamp01(t);

            Vector3 v = Vector3.zero;
            switch (Shape)
            {
                case ShapeType.Curve:
                    v = Helper.Bezier(points,t);
                    break;
                case ShapeType.Line:
                {
                    int index = 0;
                    for(int i = 0, max = distances.Length; i < max; i++)
                    {
                        if(distances[i] < t)
                        {
                            if(i == max -1)
                            {
                                index = i;
                                break;
                            }
                            t -= distances[i];
                        }
                        else
                        {
                            index = i;
                            break;
                        }
                    }
                    t = t / distances[index];
                    v = (1-t)*points[index] + t * points[index+1];
                    break;
                }
                default:
                    break;
            }
            return v;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="XUtility.Curve"/> class.
        /// </summary>
        /// <param name="point">Point.</param>
        /// <param name="shape">Shape.</param>
        public Curve(Vector3[] point, ShapeType shape)
        {
            Shape = shape;

            if (point == null || point.Length < 2)
                return;

            if(shape == ShapeType.Curve && point.Length < 3)
                return;

            points = new Vector3[point.Length];
            points [0] = point [0];

            distances = new float[point.Length - 1];
            float[] temp = new float[points.Length -1];
            float total = 0;

            for (int i = 0, max = distances.Length; i < max; i++)
            {
                points[i+1] = point[i+1];
                temp[i] = Vector3.Distance(point[i], point[i+1]);
                total += temp[i];
            }

            for (int i = 0, max = distances.Length; i < max; i++)
            {
                distances[i] = temp[i]/total;
            }
        }
    }
}

