// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;
using XUtility;

/// <summary>
/// Customer update.
/// </summary>
public class CustomerUpdate : MonoBehaviour
{
    /// <summary>
    /// Gets the instance.
    /// </summary>
    /// <value>The instance.</value>
    public static CustomerUpdate Instance
    {
        get
        {
            if(instance == null)
            {
                GameObject go = new GameObject("_CustomerUpdate");
                go.AddComponent<DontDestory>();
                instance = go.AddComponent<CustomerUpdate>();
            }
            return instance;
        }
    }

    private List<CustomerAction> updateFunctions;

    private List<CustomerAction> lateUpdateFunctions;

    private List<int> removeUpdateIndex;

    private List<int> removeLateUpdateIndex;

    private int index;

    private int count;

    private static CustomerUpdate instance;

    /// <summary>
    /// Adds the update.
    /// </summary>
    /// <param name="method">Method.</param>
    public void AddUpdate(CustomerAction method)
    {
        if (method == null)
            return;
        int i = updateFunctions.IndexOf(method);
        if (i == -1)
            updateFunctions.Add(method);
        else
            GlobalLog.LogWarning("AddUpdate has exist" + method.ToString());
    }

    /// <summary>
    /// Removes the update.
    /// </summary>
    /// <param name="method">Method.</param>
    public void RemoveUpdate(CustomerAction method)
    {
        if (method == null)
            return;
        //updateFunctions.Remove(method);
        int i = updateFunctions.IndexOf(method);
        if (i != -1)
        {
            if(removeUpdateIndex.Contains(i))
               return;
            removeUpdateIndex.Add(i);
        }
    }

    /// <summary>
    /// Adds the late update.
    /// </summary>
    /// <param name="method">Method.</param>
    public void AddLateUpdate(CustomerAction method)
    {
        if (method == null)
            return;
        lateUpdateFunctions.Add(method);
    }

    /// <summary>
    /// Removes the late update.
    /// </summary>
    /// <param name="method">Method.</param>
    public void RemoveLateUpdate(CustomerAction method)
    {
        if (method == null)
            return;
        //lateUpdateFunctions.Remove(method);
        int i = lateUpdateFunctions.IndexOf(method);
        if (i != -1)
        {
            if(removeLateUpdateIndex.Contains(i))
                return;
            removeLateUpdateIndex.Add(i);
         }
    }

    void Awake()
    {
        instance = this;
        updateFunctions = new List<CustomerAction>();
        lateUpdateFunctions = new List<CustomerAction>();
        removeUpdateIndex = new List<int>();
        removeLateUpdateIndex = new List<int>();
    }

    void Update()
    {
        for (index = 0, count = updateFunctions.Count; index < count; index++)
        {
            if(updateFunctions[index] == null)
                continue;
            try
            {
                updateFunctions[index]();
            }
            catch(System.Exception e)
            {
                XUtility.GlobalLog.Log(e.Message);
                updateFunctions[index] = null;
            }
        }

        for (index = removeUpdateIndex.Count-1; index >= 0; index--)
        {
            if(removeUpdateIndex[index] >= updateFunctions.Count)
                break;
            updateFunctions.RemoveAt(removeUpdateIndex[index]);
        }
        removeUpdateIndex.Clear();
    }

    void LateUpdate()
    {
        for (index = 0, count = lateUpdateFunctions.Count; index < count; index++)
        {
            if(lateUpdateFunctions[index] == null)
                continue;
            try
            {
                lateUpdateFunctions[index]();
            }
            catch (System.Exception e)
            {
                XUtility.GlobalLog.Log(e.Message);
                lateUpdateFunctions[index] = null;
            }
        }

        for (index = removeLateUpdateIndex.Count-1; index >= 0; index--)
        {
            if(removeLateUpdateIndex[index] >= lateUpdateFunctions.Count)
                break;
            lateUpdateFunctions.RemoveAt(removeLateUpdateIndex[index]);
        }
        removeLateUpdateIndex.Clear();
    }
}

