// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

/// <summary>
/// Global message key.
/// </summary>
public class GlobalMessageKey
{
    /// <summary>
    /// The next screen in editor.
    /// </summary>
    public const string NextScreenInEditor = "Next_Screen_InEditor_G";

    /// <summary>
    /// The player hp change.
    /// </summary>
    public const string PlayerHpChange = "Player_Hp_Change_G";

    /// <summary>
    /// The player coin change.
    /// </summary>
    public const string PlayerCoinChange = "Player_Coin_Change_G";

    /// <summary>
    /// The player get red soul.
    /// </summary>
    public const string PlayerGetRedSoul = "Player_Get_RedSoul_G";
        
    /// <summary>
    /// The player get blue soul.
    /// </summary>
    public const string PlayerGetBlueSoul = "Player_Get_BlueSoul_G";

    /// <summary>
    /// The player hit red soul.
    /// </summary>
    public const string PlayerHitRedSoul = "PlayerHitRedSoul_G";

    /// <summary>
    /// The player hit blue soul.
    /// </summary>
    public const string PlayerHitBlueSoul = "PlayerHitBlueSoul_G";

    /// <summary>
    /// The show pass time.
    /// </summary>
    public const string ShowPassTime = "ShowPassTime_G";

    /// <summary>
    /// The show guide view.
    /// </summary>
    public const string ShowGuideView = "ShowGuideView_G";

    /// <summary>
    /// The show avoid view.
    /// </summary>
    public const string ShowAvoidView = "ShowAvoidView_G";

    /// <summary>
    /// The show choose sill viem.
    /// </summary>
    public const string ShowChooseSillViem = "Show_ChooseSill_Viem_G";

    /// <summary>
    /// The load scene start.
    /// </summary>
    public const string LoadSceneStart = "Load_Scene_Start_G";

    /// <summary>
    /// The load scene end.
    /// </summary>
    public const string LoadSceneEnd = "Load_Scene_End_G";

    /// <summary>
    /// The quit scene.
    /// </summary>
    public const string QuitScene = "Quit_Scene_G";


    /// <summary>
    /// The game over.
    /// </summary>
    public const string GameOver = "Game_Over_G";

    /// <summary>
    /// The MP over.
    /// </summary>
    public const string MPOver = "Mp_Over_G";

    /// <summary>
    /// The use symbol.
    /// </summary>
    public const string UseSymbol = "UseSymbol_G";

    /// <summary>
    /// The enter battle scene.
    /// </summary>
    public const string EnterBattleScene = "EnterBattleScene_G";

    /// <summary>
    /// The battle over.
    /// </summary>
    public const string BattleOver = "BattleOver_G";

    /// <summary>
    /// The add NP.
    /// </summary>
    public const string AddNPC = "AddNPC_G";

    /// <summary>
    /// The NPC die.
    /// </summary>
    public const string NPCDie = "NPCDie_G";

    /// <summary>
    /// The kill NPC award.
    /// </summary>
    public const string KillNPCAward = "KillNPCAward_G";

    /// <summary>
    /// The avoid fail.
    /// </summary>
    public const string AvoidFail = "AvoidFail_G";

    /// <summary>
    /// The avoid ok.
    /// </summary>
    public const string AvoidOk = "AvoidOk_G";

    /// <summary>
    /// The add run NP.
    /// </summary>
    public const string AddRunNPC = "AddRunNPC_G";

    /// <summary>
    /// The use skill at run.
    /// </summary>
    public const string UseSkillAtRun = "UseSkillAtRun_G";
}

/// <summary>
/// Shape type.
/// </summary>
public enum ShapeType
{
    /// <summary>
    /// The line.
    /// </summary>
    Line,

    /// <summary>
    /// The curve.
    /// </summary>
    Curve
}

/// <summary>
/// Money type.
/// </summary>
[Flags]
public enum MoneyType
{
    /// <summary>
    /// The coin.
    /// </summary>
    Coin = 1,

    /// <summary>
    /// The crystal.
    /// </summary>
    Crystal = 2,

    /// <summary>
    /// The red soul.
    /// </summary>
    RedSoul = 4,

    /// <summary>
    /// The blue soul.
    /// </summary>
    BlueSoul = 8,
    /// <summary>
    /// The max.
    /// </summary>
    Max = 15,
}

/// <summary>
/// Rank type.
/// </summary>
public enum RankType
{
    /// <summary>
    /// The stars.
    /// </summary>
    Stars = 1,
    /// <summary>
    /// The pass level.
    /// </summary>
    PassLevel,
    /// <summary>
    /// The run dis.
    /// </summary>
    RunDis,
    /// <summary>
    /// The battle.
    /// </summary>
    Battle,
    /// <summary>
    /// The max.
    /// </summary>
    Max
}

/// <summary>
/// Resoult code.
/// </summary>
public enum CommandResoultCode
{
    /// <summary>
    /// The ok.
    /// </summary>
    Ok,
    /// <summary>
    /// The fail.
    /// </summary>
    Fail,
    /// <summary>
    /// The coin not enough.
    /// </summary>
    CoinNotEnough,
    /// <summary>
    /// The crystal not enough.
    /// </summary>
    CrystalNotEnough,
}

/// <summary>
/// Scene model.
/// </summary>
public enum SceneMode
{
    /// <summary>
    /// The unknow.
    /// </summary>
    Unknow,
    /// <summary>
    /// The run.
    /// </summary>
    Run,
    /// <summary>
    /// The coin.
    /// </summary>
    Coin,
    /// <summary>
    /// The pursue.
    /// </summary>
    Pursue,
    /// <summary>
    /// The symbol.
    /// </summary>
    Symbol,
    /// <summary>
    /// 杀戮模式.
    /// The massacre.
    /// </summary>
    Massacre,
    /// <summary>
    /// The max.
    /// </summary>
    Max
}

/// <summary>
/// Direction enum.
/// </summary>
[System.Flags]
public enum DirectionEnum
{
    /// <summary>
    /// The none.
    /// </summary>
    None,
    /// <summary>
    /// Up.
    /// </summary>
    Up = 1,
    /// <summary>
    /// Down.
    /// </summary>
    Down = 2,
    /// <summary>
    /// The left.
    /// </summary>
    Left = 4,
    /// <summary>
    /// The right.
    /// </summary>
    Right = 8,
    /// <summary>
    /// All.
    /// </summary>
    All = 15,
}

/// <summary>
/// Game over result.
/// </summary>
public enum GameOverResult
{
    /// <summary>
    /// The unknow.
    /// </summary>
    Unknow,
    /// <summary>
    /// The succeed.
    /// </summary>
    Succeed,
    /// <summary>
    /// The time over.
    /// </summary>
    TimeOver,

    /// <summary>
    /// The player die.
    /// </summary>
    PlayerDie,
}

/// <summary>
/// Game layer.
/// </summary>
public class GameLayer
{
    #region layer id
    
    /// <summary>
    /// The layer U.
    /// </summary>
    public const int LayerUI = 8;
    
    /// <summary>
    /// The layer player.
    /// </summary>
    public const int LayerPlayer = 9;

    /// <summary>
    /// The layer NP.
    /// </summary>
    public const int LayerNPC = 10;

    /// <summary>
    /// The layer walk.
    /// </summary>
    public const int LayerWalk = 11;

    /// <summary>
    /// The layer2 DUI ignore raycast.
    /// </summary>
    public const int Layer2DUIIgnoreRaycast = 12;
    
    #endregion

}

/// <summary>
/// Game tags.
/// </summary>
public class GameTags
{
    #region tags
    
    /// <summary>
    /// The tags player.
    /// </summary>
    public const string TagsPlayer = "Player";
    
    /// <summary>
    /// The tags npc.
    /// </summary>
    public const string TagsNpc = "NPC";

    /// <summary>
    /// The tags ignore press.
    /// </summary>
    public const string TagsIgnorePress = "IgnorePress";

    /// <summary>
    /// The tags user interface ignore press.
    /// </summary>
    public const string TagsUIIgnorePress = "UIIgnoreRaycast";
    
    #endregion
}

