// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace XUtility
{
    /// <summary>
    /// X player prefs.
    /// </summary>
    public class XPlayerPrefs
    {
        /// <summary>
        /// Sets the int.
        /// </summary>
        /// <param name="key">Key.</param>
        /// <param name="value">Value.</param>
        static public void SetInt(string key, int value)
        {
            PlayerPrefs.SetInt(key,value);
        }

        /// <summary>
        /// Sets the float.
        /// </summary>
        /// <param name="key">Key.</param>
        /// <param name="value">Value.</param>
        static public void SetFloat(string key, float value)
        {
            PlayerPrefs.SetFloat(key,value);
        }

        /// <summary>
        /// Sets the string.
        /// </summary>
        /// <param name="key">Key.</param>
        /// <param name="value">Value.</param>
        static public void SetString(string key, string value)
        {
            PlayerPrefs.SetString(key,value);
        }

        /// <summary>
        /// Gets the int.
        /// </summary>
        /// <returns>The int.</returns>
        /// <param name="key">Key.</param>
        /// <param name="defaultValue">Default value.</param>
        static public int GetInt(string key, int defaultValue = 0)
        {
            if( PlayerPrefs.HasKey(key))
                return PlayerPrefs.GetInt(key);
            else
                return defaultValue;
        }

        /// <summary>
        /// Gets the float.
        /// </summary>
        /// <returns>The float.</returns>
        /// <param name="key">Key.</param>
        /// <param name="defaultValue">Default value.</param>
        static public float GetFloat(string key,float defaultValue = 0)
        {
            if( PlayerPrefs.HasKey(key))
                return PlayerPrefs.GetFloat(key);
            else
                return defaultValue;
        }

       /// <summary>
       /// Gets the string.
       /// </summary>
       /// <returns>The string.</returns>
       /// <param name="key">Key.</param>
       /// <param name="defaultValue">Default value.</param>
        static public string GetString(string key,string defaultValue = "")
        {
            if( PlayerPrefs.HasKey(key))
                return PlayerPrefs.GetString(key);
            else
                return defaultValue;
        }

        /// <summary>
        /// Deletes all.
        /// </summary>
        static public void DeleteAll()
        {
            PlayerPrefs.DeleteAll();
        }
    }
}

