// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using PureMVC.Patterns;

namespace XMVC
{
    /// <summary>
    /// X application.
    /// </summary>
    public class XApplication:Facade
    {
        #region data Change Evnent
        #endregion

        #region Proxy Name
        #endregion

        #region Command Name
        /// <summary>
        /// The command start.
        /// </summary>
        public const string CommandStart = "CommandStart";
        #endregion

        /// <summary>
        /// Gets the instance.
        /// </summary>
        /// <returns>The instance.</returns>
        public static XApplication GetInstance()
        {
            if(m_instance == null)
                m_instance = new XApplication();
            return m_instance as XApplication;
        }

        /// <summary>
        /// Start this instance.
        /// </summary>
        public void Start()
        {
            SendNotification(CommandStart);
        }

        /// <summary>
        /// Registers the mediator.
        /// </summary>
        /// <param name="mediator">Mediator.</param>
        /// <param name="eventName">Event name.</param>
        public void RegisterMediator(IXMediator mediator, string eventName)
        {
            XMediator.Instance.Register(mediator, eventName);
        }

        /// <summary>
        /// Initializes the facade.
        /// </summary>
        protected override void InitializeFacade()
        {
            base.InitializeFacade();
        }

        /// <summary>
        /// Initializes the model.
        /// </summary>
        protected override void InitializeModel()
        {
            base.InitializeModel();
        }

        /// <summary>
        /// Initializes the controller.
        /// </summary>
        protected override void InitializeController()
        {
            base.InitializeController();
            m_controller.RegisterCommand(CommandStart, typeof(StartCommand));

        }

        /// <summary>
        /// Initializes the view.
        /// </summary>
        protected override void InitializeView()
        {
            base.InitializeView();
            m_view.RegisterMediator(XMediator.Instance);
        }

        private void HandleEvnetGameCore(string key, object param)
        {
            SendNotification(key, param);
        }
    }
}

