// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace XSocketClient
{
    /// <summary>
    /// Customer array.
    /// </summary>
    public class CustomerArray<T>
    {
        /// <summary>
        /// The max length.
        /// </summary>
        public int MaxLength
        {
            get;
            private set;
        }

        /// <summary>
        /// Gets the length of the current.
        /// </summary>
        /// <value>The length of the current.</value>
        public int CurrentLength
        {
            get;
            private set;
        }

        /// <summary>
        /// Gets or sets the data at the specified index.
        /// </summary>
        /// <param name="index">Index.</param>
        public T this[int index]
        {
            get
            {
                if(index >= Datas.Length) 
                {
                    throw new Exception("Out of range!");
                }

                return Datas[index];
            }
            set
            {
                if(index >= Datas.Length) 
                    return ;
                Datas[index] = value;

                if(index >= CurrentLength)
                    CurrentLength = index + 1;
            }
        }

        /// <summary>
        /// Gets the data.
        /// </summary>
        /// <value>The data.</value>
        public T[] Data
        {
            get{return Datas;}
        }

        private T[] Datas;

        /// <summary>
        /// Initializes a class.
        /// </summary>
        public CustomerArray()
        {
            MaxLength = GlobalConstantNet.BufferMaxSize;
            Datas = new T[GlobalConstantNet.BufferMaxSize];
        }

        public CustomerArray(int capacity)
        {
            MaxLength = capacity;
            Datas = new T[capacity];
        }
    }
}

