// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace XSocketClient
{
    /// <summary>
    /// VO base.
    /// </summary>
    public class NetworkVOBase : IDataWraper
    {
        /// <summary>
        /// The message I.
        /// </summary>
        public Int16 MsgID;

        /// <summary>
        /// The type of the message.
        /// </summary>
        public Int16 MsgType;

        /// <summary>
        /// The message seq.
        /// </summary>
        public Int32 MsgSeq;

        /// <summary>
        /// The type of the source.
        /// </summary>
        public byte SourceType;

        /// <summary>
        /// The type of the destination.
        /// </summary>
        public byte DestType;

        /// <summary>
        /// The destination identifier.
        /// .
        /// </summary>
        public Int32 DestId;

        /// <summary>
        /// The return code.
        /// </summary>
        public Int16 ReturnCode;

        #region IDataWraper implementation

        /// <summary>
        /// Serialization this instance.
        /// </summary>
        public virtual  CustomerArray<byte> Serialization()
        {
            CustomerArray<byte> b = new CustomerArray<byte>();

            int start = 0;
            start += BitConvert.MemoryCopy(MsgID, ref b, start);
            start += BitConvert.MemoryCopy(MsgType, ref b, start);
            start += BitConvert.MemoryCopy(MsgSeq, ref b, start);
            start += BitConvert.MemoryCopy(SourceType, ref b, start);
            start += BitConvert.MemoryCopy(DestType, ref b, start);
            start += BitConvert.MemoryCopy(Session.PlayerID, ref b, start);
            start += BitConvert.MemoryCopy(DestId, ref b, start);
            return b;
        }

        /// <summary>
        /// Deserialization the specified val and offset.
        /// </summary>
        /// <param name="val">Value.</param>
        /// <param name="offset">Offset.</param>
        public virtual int Deserialization(byte[] val, int offset)
        {
            if (val == null)
                return 0;
            MsgID = BitConvert.GetInt16(val,ref offset);
            MsgType = BitConvert.GetInt16(val,ref offset);
            MsgSeq = BitConvert.GetInt32(val,ref offset);
            SourceType = BitConvert.GetByte(val,ref offset);
            DestType = BitConvert.GetByte(val,ref offset);
            DestId = BitConvert.GetInt32(val,ref offset);
            Session.PlayerID = BitConvert.GetInt32(val,ref offset);
            if(MsgType ==GlobalConstantNet.MsgResponse)
                ReturnCode = BitConvert.GetInt16(val,ref offset);
            return offset;
        }

        #endregion

        /// <summary>
        /// Initializes a new instance of the <see cref="XSocketClient.NetworkVOBase"/> class.
        /// </summary>
        public NetworkVOBase()
        {
            MsgType = GlobalConstantNet.MsgRequest;
            MsgSeq = 111;
            DestType = NetObjectType.FE_PLAYER;
            SourceType = NetObjectType.FE_CLIENT;
        }

        /// <summary>
        /// Gets the V.
        /// </summary>
        /// <returns>The V.</returns>
        /// <param name="val">Value.</param>
        /// <param name="offset">Offset.</param>
        /// <typeparam name="T">The 1st type parameter.</typeparam>
        public static T GetVO<T>(byte[] val, int offset = 0)
            where T : NetworkVOBase, new()
        {
            T t = new T();
            t.Deserialization(val, offset);
            return t;
        }
    }
}

