// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace XSocketClient
{
    /// <summary>
    /// Register.
    /// </summary>
    public class Register:NetworkVOBase
    {
        /// <summary>
        /// The name.
        /// </summary>
        public string Name;
        
        /// <summary>
        /// The password.
        /// </summary>
        public string Password;

        /// <summary>
        /// Serialization this instance.
        /// </summary>
        public override CustomerArray<byte> Serialization()
        {
            CustomerArray<byte> b = base.Serialization();
            if(b == null)
                return null;
            
            int offset = b.CurrentLength;
            offset += BitConvert.MemoryCopy(Name, ref b, offset);
            offset += BitConvert.MemoryCopy(Password, ref b, offset);
            
            return b;
        }

        /// <summary>
        /// Deserialization the specified val and offset.
        /// </summary>
        /// <param name="val">Value.</param>
        /// <param name="offset">Offset.</param>
        public override int Deserialization(byte[] val, int offset)
        {
            int index = base.Deserialization(val, offset);

            Session.Uid = BitConvert.GetUInt64(val, ref index);
            return index;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="XSocketClient.Register"/> class.
        /// </summary>
        public Register()
        {
            MsgID = GlobalConstantNet.CodeRegister;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="XSocketClient.Register"/> class.
        /// </summary>
        /// <param name="name">Name.</param>
        /// <param name="pwd">Pwd.</param>
        public Register(string name, string pwd)
        {
            MsgID = GlobalConstantNet.CodeRegister;
            DestType = NetObjectType.FE_GAMEROOMMNG;
            DestId = 0;
            Name = name;
            Password = pwd;
        }
    }
}

