// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace XSocketClient
{
    /// <summary>
    /// Room info.
    /// </summary>
    public class RoomInfo :NetworkVOBase
    {
        private int mRoomType;

        /// <summary>
        /// Deserialization the specified val and offset.
        /// </summary>
        /// <param name="val">Value.</param>
        /// <param name="offset">Offset.</param>
        public override int Deserialization(byte[] val, int offset)
        {
            int index = base.Deserialization(val, offset);

            index += 2; // gameType.
            Session.RoomId = BitConvert.GetInt32(val, ref index);
            index += 4;//serverID.
            Session.ServerPort = BitConvert.GetUInt16(val, ref index);
            Session.ServerIP = BitConvert.GetString(val, ref index);
            return index;
        }

        /// <summary>
        /// Serialization this instance.
        /// </summary>
        public override CustomerArray<byte> Serialization()
        {
            CustomerArray<byte> b = base.Serialization();
            if(b == null)
                return null;
            
            int offset = b.CurrentLength;
            offset += BitConvert.MemoryCopy((UInt64)Session.Uid, ref b, offset);
            offset += BitConvert.MemoryCopy(0, ref b, offset); //time.
            offset += BitConvert.MemoryCopy((Int16)1, ref b, offset); // gameType.
            offset += BitConvert.MemoryCopy(mRoomType, ref b, offset);
            
            return b;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="XSocketClient.RoomInfo"/> class.
        /// </summary>
        public RoomInfo()
        {
            MsgID = GlobalConstantNet.CodeGetRoomInfo;
            mRoomType = 1;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="XSocketClient.RoomInfo"/> class.
        /// </summary>
        /// <param name="roomType">Room type.</param>
        public RoomInfo(int roomType)
        {
            mRoomType = roomType;
            MsgID = GlobalConstantNet.CodeGetRoomInfo;
        }
    }

    /// <summary>
    /// Login room.
    /// </summary>
    public class LoginRoomVo: NetworkVOBase
    {
        /// <summary>
        /// Deserialization the specified val and offset.
        /// </summary>
        /// <param name="val">Value.</param>
        /// <param name="offset">Offset.</param>
        public override int Deserialization(byte[] val, int offset)
        {
            int index = base.Deserialization(val, offset);

            Session.PlayerID = BitConvert.GetInt32(val, ref index);
            Session.DialogId = Session.PlayerID;
            return index;
        }

        /// <summary>
        /// Serialization this instance.
        /// </summary>
        public override CustomerArray<byte> Serialization()
        {
            CustomerArray<byte> b = base.Serialization();
            if(b == null)
                return null;

            int offset = b.CurrentLength;
            offset += BitConvert.MemoryCopy((UInt64)Session.Uid, ref b, offset);
            offset += BitConvert.MemoryCopy((short)1, ref b, offset);//gameType.
            offset += BitConvert.MemoryCopy(0, ref b, offset); //time.
            offset += BitConvert.MemoryCopy(1, ref b, offset); // clientVersion.

            return b;
        }

        /// <summary>
        /// Initializes class.
        /// </summary>
        public LoginRoomVo()
        {
            MsgID = GlobalConstantNet.CodeLoginGame;
            DestType = NetObjectType.FE_PLAYER;
        }
    }

    /// <summary>
    /// Enter room.
    /// </summary>
    public class EnterRoomVO:NetworkVOBase
    {
        public CustomerArray<TableInfo> tables
        {
            get;
            private set;
        }

        /// <summary>
        /// Deserialization the specified val and offset.
        /// </summary>
        /// <param name="val">Value.</param>
        /// <param name="offset">Offset.</param>
        public override int Deserialization(byte[] val, int offset)
        {
            int index = base.Deserialization(val, offset);
            index += 2;//gameId;
            index += 2;//roomType;

            short num = BitConvert.GetInt16(val, ref index); //table num.
            tables = new CustomerArray<TableInfo>(num);
            num = BitConvert.GetInt16(val, ref index); //player num.
            TableInfo table;
            for (int i = 0, max = tables.MaxLength; i < max; i++)
            {
                table = new TableInfo();
                table.ID = BitConvert.GetInt32(val,ref index);
                table.Status = BitConvert.GetUInt16(val, ref index);
                tables[i] = table;
            }
            return index;
        }

        /// <summary>
        /// Serialization this instance.
        /// </summary>
        public override CustomerArray<byte> Serialization()
        {
            CustomerArray<byte> b = base.Serialization();
            if(b == null)
                return null;

            int offset = b.CurrentLength;
            offset += BitConvert.MemoryCopy((UInt64)Session.Uid, ref b, offset);
            offset += BitConvert.MemoryCopy(0, ref b, offset); //time.

            return b;
        }

        public EnterRoomVO()
        {
            MsgID = GlobalConstantNet.CodeEnterRoom;
            DestType = NetObjectType.FE_ROOM;
            DestId = Session.RoomId;
        }
    }

    public class LeaveRoomVO:NetworkVOBase
    {
        /// <summary>
        /// Serialization this instance.
        /// </summary>
        public override CustomerArray<byte> Serialization()
        {
            CustomerArray<byte> b = base.Serialization();
            if(b == null)
                return null;

            int offset = b.CurrentLength;
            offset += BitConvert.MemoryCopy((UInt64)Session.Uid, ref b, offset);
            offset += BitConvert.MemoryCopy(0, ref b, offset); //time.

            return b;
        }

        public LeaveRoomVO()
        {

            MsgID = GlobalConstantNet.CodeLeaveRoom;
            DestType = NetObjectType.FE_ROOM;
            DestId = Session.RoomId;
        }
    }
}

