// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace XMVC
{
    /// <summary>
    /// IX mediator.
    /// 
    /// </summary>
    public interface IXMediator
    {
        /// <summary>
        /// Refreshs the mediator.
        /// 当收到相关数据变化时，用于更新界面的接口.
        /// </summary>
        void RefreshMediator(string key, object param);
    }
}

