// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using PureMVC.Patterns;
using PureMVC.Interfaces;
using XUtility;

namespace XMVC
{
    /// <summary>
    /// X mediator.
    /// </summary>
    public class XMediator : Mediator
    {
        /// <summary>
        /// Gets the instance.
        /// </summary>
        /// <value>The instance.</value>
        public static XMediator Instance
        {
            get { return instance;}
        }

        private static XMediator instance;

        private Dictionary<string, List<IXMediator>> observer;

        private LogWraper log;

        /// <summary>
        /// Register the specified mediator and eventName.
        /// </summary>
        /// <param name="mediator">Mediator.</param>
        /// <param name="eventName">Event name.</param>
        public void Register(IXMediator mediator, string eventName)
        {
            if (mediator == null || string.IsNullOrEmpty(eventName))
                return;

            if (!observer.ContainsKey(eventName))
            {
                observer.Add(eventName, new List<IXMediator>());
                PureMVC.Core.View.Instance.RegisterObserver(eventName, new Observer(NotifyToMediator,this));

            }
            observer [eventName].Add(mediator);
        }

        /// <summary>
        /// Retrieve the specified eventName.
        /// </summary>
        /// <param name="eventName">Event name.</param>
        public List<IXMediator> Retrieve(string eventName)
        {
            if (string.IsNullOrEmpty(eventName) || !observer.ContainsKey(eventName))
                return null;

            return observer [eventName];
        }

        /// <summary>
        /// Notifies to mediator.
        /// </summary>
        /// <param name="notification">Notification.</param>
        public void NotifyToMediator(INotification notification)
        {
            if (notification == null)
                return;

            List<IXMediator> ms = null;

//            switch (notification.Name)
//            {
//                case XApplication.EventPlayerInfoChange:
                    ms = Retrieve(notification.Name);
//                    break;
//                default:
//                    break;
//            }

            if (ms != null)
            {
                for(int i = 0, max = ms.Count; i < max; i++)
                    ms[i].RefreshMediator(notification.Name, notification.Body);
            }
        }

        static XMediator()
        {
            instance = new XMediator();
        }

        /// <summary>
        /// Initializes a new instance class.
        /// </summary>
        public XMediator()
            :base("XMediator")
        {
            observer = new Dictionary<string, List<IXMediator>>();
            log = LogWraper.GetLog<XMediator>();
        }
    }
}

