// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace XUtility
{
    /// <summary>
    /// FSM machine.
    /// </summary>
    public class FSMMachine
    {
           
        /// <summary>
        /// Gets the state of the current.
        /// </summary>
        /// <value>The state of the current.</value>
        public FSMState currentState{ get; private set;}

        /// <summary>
        /// The states.
        /// </summary>
        protected Dictionary<int, FSMState> states;

        /// <summary>
        /// Sets the state.
        /// </summary>
        /// <param name="stateId">State identifier.</param>
        public void SetState(int stateId)
        {
            if (states.ContainsKey(stateId))
            {
                FSMState state = states [stateId];
                SetState(state);
            }
        }

        /// <summary>
        /// Sets the state.
        /// </summary>
        /// <param name="state">State.</param>
        public void SetState(FSMState state)
        {
            if (state == null)
                return;
            if (!states.ContainsKey(state.ID))
                return;
            if (state.CanInState())
            {
                if(currentState != null)
                {
                    if(!currentState.CanQuitState())
                        return;
                    currentState.Quit();
                }
                currentState = state;
                state.Start();
            }
        }

        /// <summary>
        /// Adds the state.
        /// </summary>
        /// <param name="state">State.</param>
        public void AddState(FSMState state)
        {
            if (state == null || states.ContainsKey(state.ID))
                return;
            state.Machine = this;
            states.Add(state.ID, state);
        }

        /// <summary>
        /// Gets the state.
        /// </summary>
        /// <returns>The state.</returns>
        /// <param name="id">Identifier.</param>
        public FSMState GetState(int id)
        {
            if (states.ContainsKey(id))
                return states [id];
            return null;
        }

        /// <summary>
        /// Adds the transmission.
        /// </summary>
        /// <param name="eventId">Event identifier.</param>
        /// <param name="fromState">From state.</param>
        /// <param name="toState">To state.</param>
        public void AddTransmission(int eventId, int fromState, int toState)
        {
            FSMState f = GetState(fromState);
            if (f == null)
                return;

            FSMState t = GetState(toState);
            if (t == null)
                return;

            f.AddTransmission(eventId, t.ID);
        }

        /// <summary>
        /// Transmit the specified eventId.
        /// </summary>
        /// <param name="eventId">Event identifier.</param>
        public bool Transmit(int eventId)
        {
            if (currentState == null)
                return false;

            int stateId = currentState.GetTransmissioin(eventId);
            FSMState state = GetState(stateId);
            if (state == null)
                return false;

            if (state.CanInState() && currentState.CanQuitState())
            {
                currentState.Quit();

                currentState = state;

                currentState.Start();

                return true;
            }

            return false;
        }

        /// <summary>
        /// Transmit the specified eventId and param.
        /// </summary>
        /// <param name="eventId">Event identifier.</param>
        /// <param name="param">Parameter.</param>
        public bool Transmit(int eventId, object param)
        {
            if (currentState == null)
                return false;
            
            int stateId = currentState.GetTransmissioin(eventId);
            FSMState state = GetState(stateId);
            if (state == null)
                return false;
            
            if (state.CanInState() && currentState.CanQuitState())
            {
                currentState.Quit();
                
                currentState = state;
                
                currentState.Start(param);
                
                return true;
            }
            
            return false;
        }

        /// <summary>
        /// Update this instance.
        /// </summary>
        public void Update()
        {
            if (currentState != null)
                currentState.Run();
        }
        /// <summary>
        /// Initializes a new instance.
        /// </summary>
        public FSMMachine()
        {
            states = new Dictionary<int, FSMState>();
        }
    }
}

