// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace XUtility
{
    /// <summary>
    /// FSM state.
    /// </summary>
    public abstract class FSMState
    {
        /// <summary>
        /// The I.
        /// </summary>
        public int ID;

        /// <summary>
        /// The machine.
        /// </summary>
        public FSMMachine Machine;

        /// <summary>
        /// The transmissions.
        /// </summary>
        protected Dictionary<int, int> transmissions;

        /// <summary>
        /// Start this instance.
        /// </summary>
        public abstract void Start();

        /// <summary>
        /// Start the specified param.
        /// </summary>
        /// <param name="param">Parameter.</param>
        public virtual void Start(object param){}

        /// <summary>
        /// Quit this instance.
        /// </summary>
        public abstract void Quit();

        /// <summary>
        /// Run this instance.
        /// </summary>
        public abstract void Run();

        /// <summary>
        /// Determines whether this instance can in state.
        /// </summary>
        /// <returns><c>true</c> if this instance can in state; otherwise, <c>false</c>.</returns>
        public virtual bool CanInState()
        {
            return true;
        }

        /// <summary>
        /// Determines whether this instance can quit state.
        /// </summary>
        /// <returns><c>true</c> if this instance can quit state; otherwise, <c>false</c>.</returns>
        public virtual bool CanQuitState()
        {
            return true;
        }

        /// <summary>
        /// Adds the transmission.
        /// </summary>
        /// <param name="eventId">Event identifier.</param>
        /// <param name="state">State.</param>
        public void AddTransmission(int eventId, FSMState state)
        {
            if (state == null)
                return;
            AddTransmission(eventId, state.ID);
        }

        /// <summary>
        /// Adds the transmission.
        /// </summary>
        /// <param name="eventId">Event identifier.</param>
        /// <param name="stateId">State identifier.</param>
        public void AddTransmission(int eventId, int stateId)
        {
            if (transmissions.ContainsKey(eventId))
                return;
            transmissions.Add(eventId, stateId);
        }

        /// <summary>
        /// Gets the transmissioin.
        /// </summary>
        /// <returns>The transmissioin.</returns>
        /// <param name="evnetId">Evnet identifier.</param>
        public int GetTransmissioin(int evnetId)
        {
            if (transmissions.ContainsKey(evnetId))
                return transmissions [evnetId];

            return -1;
        }

        /// <summary>
        /// Initializes a new instance.
        /// </summary>
        public FSMState()
        {
            ID = 0;
            transmissions = new Dictionary<int, int>();
        }

        /// <summary>
        /// Initializes a new instance.
        /// </summary>
        /// <param name="idValue">Identifier value.</param>
        public FSMState(int idValue)
        {
            ID = idValue;
            transmissions = new Dictionary<int, int>();
        }
    }
}

