// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
#if UNITY_WP8
#else
using System.Net.NetworkInformation;
#endif

namespace XSocketClient
{
    /// <summary>
    /// Ping wraper.
    /// </summary>
    public class PingWraper
    {
        #if UNITY_WP8
        #else
        private Ping pingSender;

        private PingOptions options;

        /// <summary>
        /// Initializes a new instance  class.
        /// </summary>
        public PingWraper()
        {
            pingSender = new Ping();
            options = new PingOptions();
            options.DontFragment = true;
        }
#endif
    }
}

