// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace XSocketClient
{
    /// <summary>
    /// I data wraper.
    /// the object contain:int, int64, bool, string,byte.
    /// </summary>
    public interface IDataWraper
    {
//        /// <summary>
//        /// Serialization this instance.
//        /// </summary>
//        object[] Serialization();
//
//        /// <summary>
//        /// Deserialization the specified val and offset.
//        /// </summary>
//        /// <param name="val">Value.</param>
//        /// <param name="offset">Offset.</param>
//        int Deserialization(object[] val, int offset);

        /// <summary>
        /// Serialization this instance.
        /// </summary>
        CustomerArray<byte> Serialization();

        /// <summary>
        /// Deserialization the specified val and offset.
        /// </summary>
        /// <param name="val">Value.</param>
        /// <param name="offset">Offset.</param>
        int Deserialization(byte[] val, int offset);
    }
}

