// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace XSocketClient
{
    /// <summary>
    /// I net.
    /// </summary>
    public interface INet
    {
        /// <summary>
        /// Gets a value indicating whether this <see cref="XSocketClient.INet"/> is connected.
        /// </summary>
        /// <value><c>true</c> if connected; otherwise, <c>false</c>.</value>
        bool Connected{ get;}

        /// <summary>
        /// Connect the specified ip and port.
        /// </summary>
        /// <param name="ip">Ip.</param>
        /// <param name="port">Port.</param>
        bool Connect(string ip, int port);

        /// <summary>
        /// Disconnect this instance.
        /// </summary>
        bool Disconnect();

        /// <summary>
        /// Sends the request.
        /// </summary>
        /// <returns><c>true</c>, if request was sent, <c>false</c> otherwise.</returns>
        /// <param name="data">Data.</param>
        bool SendRequest(IDataWraper data);

        /// <summary>
        /// Handles the event.
        /// </summary>
        /// <param name="code">Code.</param>
        /// <param name="data">Data.</param>
        void HandleEvent(Int16 code, byte[] data);
        /// <summary>
        /// Handles the response.
        /// </summary>
        /// <param name="returnCode">Return code.</param>
        /// <param name="code">Code.</param>
        /// <param name="data">Data.</param>
        void HandleResponse(int returnCode, Int16 code, byte[] data);

        /// <summary>
        /// Update this instance.
        /// </summary>
        void Update();
    }
}

