// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
#define BIG_ENDIAN
using System;

namespace XSocketClient
{
    /// <summary>
    /// Bit convert.
    /// </summary>
    public class BitConvert
    {
       /// <summary>
       /// Tos the bytes.
       /// </summary>
       /// <returns>The bytes.</returns>
       /// <param name="value">Value.</param>
       /// <param name="buff">Buff.</param>
       /// <param name="offset">Offset.</param>
        public static int ToBytes(char value, ref byte[] buff, int offset)
        {
            if (buff == null || offset >= buff.Length)
                return -1;

            buff [offset] = (byte)value;

            return 1;
        }

        /// <summary>
        /// Tos the bytes.
        /// </summary>
        /// <returns>The bytes.</returns>
        /// <param name="value">If set to <c>true</c> value.</param>
        public static byte[] ToBytes(bool value)
        {
            byte[] ret = new byte[1];
            //MemeoryCopy(value, ref ret, 0);
            return ret;
        }

        /// <summary>
        /// Tos the bytes.
        /// </summary>
        /// <returns>The bytes.</returns>
        /// <param name="value">Value.</param>
        public static byte[] ToBytes(Int16 value)
        {
            byte[] ret = new byte[2];
            #if BIG_ENDIAN 
            ret [1] =(byte)( value & 0xff);
            ret [0] = (byte)((value & 0xff00) >> 8);
            #else
            ret [0] =(byte)( value & 0xff);
            ret [1] = (byte)((value & 0xff00) >> 8);
            #endif
            return ret;
        }

       

        /// <summary>
        /// Tos the bytes.
        /// </summary>
        /// <returns>The bytes.</returns>
        /// <param name="value">Value.</param>
        public static byte[] ToBytes(Int32 value)
        {
            byte[] ret = new byte[4];
            #if BIG_ENDIAN 
            ret [3] =(byte)( value & 0xff);
            ret [2] = (byte)(( value & 0xff00) >> 8);
            ret [1] =(byte)( (value & 0xff0000) >> 16);
            ret [0] = (byte)(( value & 0xff000000) >> 24);
            #else
            ret [0] = (byte)( value & 0xff);
            ret [1] = (byte)((value & 0xff00) >> 8);
            ret [2] = (byte)((value & 0xff0000) >> 16);
            ret [3] = (byte)((value & 0xff000000) >> 24);
            #endif
            return ret;
        }

//        public static byte[] ToBytes(Int64 value)
//        {
//            byte[] ret = new byte[8];
//            #if BIG_ENDIAN  
//            ret [7] = (byte)( value & 0xff);
//            ret [6] = (byte)((value & 0xff00) >> 8);
//            ret [5] = (byte)((value & 0xff0000) >> 16);
//            ret [4] = (byte)((value & 0xff000000) >> 24);
//            ret [3] = (byte)((value & 0xff00000000) >> 32);
//            ret [2] = (byte)((value & 0xff0000000000) >> 40);
//            ret [1] = (byte)((value & 0xff000000000000) >> 48);
//            ret [0] = (byte)((value & 0xff00000000000000) >> 56);
//            #else
//            ret [0] = (byte)( value & 0xff);
//            ret [1] = (byte)((value & 0xff00) >> 8);
//            ret [2] = (byte)((value & 0xff0000) >> 16);
//            ret [3] = (byte)((value & 0xff000000) >> 24);
//            ret [4] = (byte)((value & 0xff00000000) >> 32);
//            ret [5] = (byte)((value & 0xff0000000000) >> 40);
//            ret [6] = (byte)((value & 0xff000000000000) >> 48);
//            ret [7] = (byte)((value & 0xff00000000000000) >> 56);
//            #endif
//            return ret;
//        }

        /// <summary>
        /// Tos the bytes.
        /// </summary>
        /// <returns>The bytes.</returns>
        /// <param name="value">value.</param>
        public static byte[] ToBytes(UInt64 value)
        {
            byte[] ret = new byte[8];
            #if BIG_ENDIAN 
            ret [7] = (byte)( value & 0xff);
            ret [6] = (byte)((value & 0xff00) >> 8);
            ret [5] = (byte)((value & 0xff0000) >> 16);
            ret [4] = (byte)((value & 0xff000000) >> 24);
            ret [3] = (byte)((value & 0xff00000000) >> 32);
            ret [2] = (byte)((value & 0xff0000000000) >> 40);
            ret [1] = (byte)((value & 0xff000000000000) >> 48);
            ret [0] = (byte)((value & 0xff00000000000000) >> 56);
            #else
            ret [0] = (byte)( value & 0xff);
            ret [1] = (byte)((value & 0xff00) >> 8);
            ret [2] = (byte)((value & 0xff0000) >> 16);
            ret [3] = (byte)((value & 0xff000000) >> 24);
            ret [4] = (byte)((value & 0xff00000000) >> 32);
            ret [5] = (byte)((value & 0xff0000000000) >> 40);
            ret [6] = (byte)((value & 0xff000000000000) >> 48);
            ret [7] = (byte)((value & 0xff00000000000000) >> 56);
            #endif
            return ret;
        }

        /// <summary>
        /// Memeories the copy.
        /// </summary>
        /// <returns>The copy.</returns>
        /// <param name="value">Value.</param>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">offset.</param>
        public static int MemoryCopy(byte value, ref CustomerArray<byte> buff, int offset)
        {
            if (buff == null || offset >= buff.MaxLength)
                return 0;
            
            buff [offset] = value;
            
            return 1;
        }

        /// <summary>
        /// Memeories the copy.
        /// </summary>
        /// <returns>The copy.</returns>
        /// <param name="value">Value.</param>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">offset.</param>
        public static int MemoryCopy(char value, ref CustomerArray<byte> buff, int offset)
        {
            if (buff == null || offset >= buff.MaxLength)
                return 0;
            
            buff [offset] = (byte)value;
            
            return 1;
        }

        
        /// <summary>
        /// Memeories the copy.
        /// </summary>
        /// <returns>The copy.</returns>
        /// <param name="value">If set to <c>true</c> value.</param>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">offset.</param>
        public static int MemoryCopy(bool value, ref CustomerArray<byte> buff, int offset)
        {
            if (buff == null || offset >= buff.MaxLength)
                return 0;
            if(value)
                buff[offset] = 1;
            else
                buff[offset] = 0;
            return 1;
        }

        /// <summary>
        /// Memeories the copy.
        /// </summary>
        /// <returns>The copy.</returns>
        /// <param name="value">Value.</param>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">offset.</param>
        public static int MemoryCopy(Int16 value, ref CustomerArray<byte> buff, int offset)
        {
            if (buff == null || offset > buff.MaxLength - 2)
                return 0;
            #if BIG_ENDIAN 
            buff [offset + 1] =(byte)( value & 0xff);
            buff [offset + 0] = (byte)((value & 0xff00) >> 8);
            #else
            buff [offset + 0] =(byte)( value & 0xff);
            buff [offset + 1] = (byte)((value & 0xff00) >> 8);
            #endif
            
            return 2;
        }

        /// <summary>
        /// Memeories the copy.
        /// </summary>
        /// <returns>The copy.</returns>
        /// <param name="value">Value.</param>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">offset.</param>
        public static int MemoryCopy(Int32 value, ref CustomerArray<byte> buff, int offset)
        {
            if (buff == null || offset > buff.MaxLength - 4)
                return 0;
            #if BIG_ENDIAN 
            buff [offset + 3] =(byte)( value & 0xff);
            buff [offset + 2] = (byte)(( value & 0xff00) >> 8);
            buff [offset + 1] =(byte)( (value & 0xff0000) >> 16);
            buff [offset + 0] = (byte)(( value & 0xff000000) >> 24);
            #else
            buff [offset + 0] = (byte)( value & 0xff);
            buff [offset + 1] = (byte)((value & 0xff00) >> 8);
            buff [offset + 2] = (byte)((value & 0xff0000) >> 16);
            buff [offset + 3] = (byte)((value & 0xff000000) >> 24);
            #endif
            return 4;
        }

        /// <summary>
        /// Memeories the copy.
        /// </summary>
        /// <returns>The copy.</returns>
        /// <param name="value">Value.</param>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">offset.</param>
        public static int MemoryCopy(UInt64 value, ref CustomerArray<byte> buff, int offset)
        {
            if (buff == null || offset >= buff.MaxLength - 8)
                return 0;
            #if BIG_ENDIAN 
            buff [offset + 7] = (byte)( value & 0xff);
            buff [offset + 6] = (byte)((value & 0xff00) >> 8);
            buff [offset + 5] = (byte)((value & 0xff0000) >> 16);
            buff [offset + 4] = (byte)((value & 0xff000000) >> 24);
            buff [offset + 3] = (byte)((value & 0xff00000000) >> 32);
            buff [offset + 2] = (byte)((value & 0xff0000000000) >> 40);
            buff [offset + 1] = (byte)((value & 0xff000000000000) >> 48);
            buff [offset + 0] = (byte)((value & 0xff00000000000000) >> 56);
            #else
            buff [offset + 0] = (byte)( value & 0xff);
            buff [offset + 1] = (byte)((value & 0xff00) >> 8);
            buff [offset + 2] = (byte)((value & 0xff0000) >> 16);
            buff [offset + 3] = (byte)((value & 0xff000000) >> 24);
            buff [offset + 4] = (byte)((value & 0xff00000000) >> 32);
            buff [offset + 5] = (byte)((value & 0xff0000000000) >> 40);
            buff [offset + 6] = (byte)((value & 0xff000000000000) >> 48);
            buff [offset + 7] = (byte)((value & 0xff00000000000000) >> 56);
            #endif
            return 8;
        }

        /// <summary>
        /// Memories the copy.
        /// </summary>
        /// <returns>The copy.</returns>
        /// <param name="value">Value.</param>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">Offset.</param>
        public static int MemoryCopy(string value, ref CustomerArray<byte> buff, int offset)
        {
            if (string.IsNullOrEmpty(value))
                return 0;
            char[] c = value.ToCharArray();

            if (buff == null || offset >= buff.MaxLength - 2 - c.Length || c.Length < 1)
                return 0;
            offset += MemoryCopy((Int16)c.Length, ref buff, offset);
            for (int i = 0, max = c.Length; i < max; i++)
                buff [offset + i] = (byte)c [i];
            return 2 + c.Length;
        }

        //public static int Memeory

        /// <summary>
        /// Gets the byte.
        /// </summary>
        /// <returns>The byte.</returns>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">Offset.</param>
        public static byte GetByte(byte[] buff, ref int offset)
        {
            if (buff == null || offset >= buff.Length)
                return 0;
            offset++;
            return buff [offset - 1];
        }

        /// <summary>
        /// Gets the bool.
        /// </summary>
        /// <returns><c>true</c>, if bool was gotten, <c>false</c> otherwise.</returns>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">offset.</param>
        public static bool GetBool(byte[] buff, ref int offset)
        {
            if (buff == null || offset >= buff.Length)
                return false;
            if (buff [offset] == 1)
            {
                offset++;
                return true;
            } else
            {
                offset++;
                return false;
            }
        }

        /// <summary>
        /// Gets the int16.
        /// </summary>
        /// <returns>The int16.</returns>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">offset.</param>
        public static Int16 GetInt16(byte[] buff, ref int offset)
        {
            if (buff == null || offset > buff.Length-2)
                return 0;
            offset+=2;
            
            #if BIG_ENDIAN 
            return (Int16)( ((Int16)buff [offset - 2] << 8) + buff [offset - 1] );
            #else
            #endif
        }

        /// <summary>
        /// Gets the U int16.
        /// </summary>
        /// <returns>The U int16.</returns>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">Offset.</param>
        public static UInt16 GetUInt16(byte[] buff, ref int offset)
        {
            if (buff == null || offset > buff.Length-2)
                return 0;
            offset+=2;

            #if BIG_ENDIAN 
            return (UInt16)( ((UInt16)buff [offset - 2] << 8) + buff [offset - 1] );
            #else
            #endif
        }

        /// <summary>
        /// Gets the int32.
        /// </summary>
        /// <returns>The int32.</returns>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">offset.</param>
        public static Int32 GetInt32(byte[] buff, ref int offset)
        {
            if (buff == null || offset > buff.Length-4)
                return 0;
            offset+=4;
            
            #if BIG_ENDIAN 
            return (buff [offset - 4] << 24) + (buff [offset - 3] << 16) + (buff [offset - 2] << 8) + buff [offset - 1];
            #else
            #endif
        }


        /// <summary>
        /// Gets the U int64.
        /// </summary>
        /// <returns>The U int64.</returns>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">offset.</param>
        public static UInt64 GetUInt64(byte[] buff, ref int offset)
        {
            if (buff == null || offset > buff.Length-8)
                return 0;
            offset+=8;

            #if BIG_ENDIAN 
            return (UInt64)(((UInt64)buff [offset - 8] << 56) + ((UInt64)buff [offset - 7] << 48) + ((UInt64)buff [offset - 6] << 40) + ((UInt64)buff [offset - 5] << 32) + 
                            ((UInt64)buff [offset - 4] << 24) + ((UInt64)buff [offset - 3] << 16) + ((UInt64)buff [offset - 2] << 8) + buff [offset - 1]);
            #else
            #endif
        }

        /// <summary>
        /// Gets the string.
        /// </summary>
        /// <returns>The string.</returns>
        /// <param name="buff">Buff.</param>
        /// <param name="offset">Offset.</param>
        public static string GetString(byte[] buff, ref int offset)
        {
            if (buff == null || offset > buff.Length-2)
                return null;

            Int16 length = GetInt16(buff, ref offset);
            char[] c = new char[length];
            for (int i = 0, max = length; i< max; i++)
            {
                c[i] = (char)buff[offset + i];
            }
            offset += length;
            return new string(c);
        }
    }
}

