// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace XSocketClient
{
    /// <summary>
    /// Global constant.
    /// </summary>
    public class GlobalConstantNet
    {
        /// <summary>
        /// The size of the buffer max.
        /// </summary>
        public const Int32 BufferMaxSize = 2048;

        #region Operation Code

        /// <summary>
        /// The code login game.
        /// 链接到房间svr而非loginsrv.
        /// </summary>
        public const Int16 CodeLoginGame = 101;

        /// <summary>
        /// The code enter room.
        /// </summary>
        public const Int16 CodeEnterRoom = 104;

        /// <summary>
        /// The code leave room.
        /// </summary>
        public const Int16 CodeLeaveRoom = 105;

        /// <summary>
        /// The code play game.
        /// </summary>
        public const Int16 CodePlayGame = 107;

        /// <summary>
        /// The code sitdown.
        /// </summary>
        public const Int16 CodeSitdown = 111;

        /// <summary>
        /// The code standup.
        /// </summary>
        public const Int16 CodeStandup = 112;

        /// <summary>
        /// The codelogin.
        /// </summary>
        public const Int16 Codelogin = 160;
        /// <summary>
        /// The code update score.
        /// </summary>
        public const Int16 CodeUpdateScore = 161;

        /// <summary>
        /// The code get rank.
        /// </summary>
        public const Int16 CodeGetRank = 162;
        /// <summary>
        /// The code register.
        /// </summary>
        public const Int16 CodeRegister = 163;

        /// <summary>
        /// The code sign in.
        /// </summary>
        public const Int16 CodeSignIn = 164;

        /// <summary>
        /// The code share.
        /// </summary>
        public const Int16 CodeShare = 165;

        /// <summary>
        /// The code get sign in info.
        /// </summary>
        public const Int16 CodeGetSignInInfo = 166;

        /// <summary>
        /// The code get room info.
        /// </summary>
        public const Int16 CodeGetRoomInfo = 801;
        #endregion

        #region Msg Type
        /// <summary>
        /// The message request.
        /// </summary>
        public const Int16 MsgRequest = 0;
        /// <summary>
        /// The message response.
        /// </summary>
        public const Int16 MsgResponse = 1;

        /// <summary>
        /// The message evnet.
        /// </summary>
        public const Int16 MsgEvnet = 2;
        #endregion

        //public 
    }

    /// <summary>
    /// Net data type.
    /// </summary>
    public class NetDataType
    {
        /// <summary>
        /// The byte.
        /// </summary>
        public const byte BYTE = 0x00;

        /// <summary>
        /// The bool.
        /// </summary>
        public const byte BOOL = 0x10;

        /// <summary>
        /// The int32.
        /// </summary>
        public const byte INT32 = 0x20;

        /// <summary>
        /// The int64.
        /// </summary>
        public const byte INT64 = 0x30;

        /// <summary>
        /// The string.
        /// </summary>
        public const byte STRING = 0x40;
    }

    /// <summary>
    /// Return code.
    /// </summary>
    public enum ReturnCodeEnum
    {
        Succeed = 0,
        Err_System = 1,
        Err_Unknow = 2,      //未知错误
        Err_InvalidDestFE   =   1,          //非法的目的实体
        Err_InvalidSrcFE    =   2,          //非法的源实体
        Err_MultiLogin      =   3,          //重复登录
        Err_InvalidUin      =   4,          //非法的身份，主要用于身份验证未通过时
        Err_ServerFull      =   5,          //表示server的容量已满，需要玩家换地方
        Err_NoInfo          =   6,          //无法取得玩家的资料，请重试
        Err_InvalidServerID =   7,          //无效的ServerID号
        Err_InvalidRoomID   =   8,          //无效的RoomID号
        Err_InvalidTableID  =   9,          //无效的桌号
        Err_InvalidPlayerID =   10,         //无效的玩家编号
        Err_ServersOverFlow =   11,         //在拉指定Server的房间时，指定的Server过多
        Err_PlayersOverFlow =   12,         //在拉指定玩家的信息时，制定的Player过多
        Err_InvalidCfg      =   13,         //更新配置信息时，提供的配值非法
        Err_StoreCfgFailed  =   14,         //更新配置信息时，配置信息存储失败
        Err_InvalidSeat     =   15,         //玩家坐下可能返回的错误 //坐下时，指定的座位号非法
        Err_NoSeat          =   16,         //坐下时，指定的座位已经有人了
        
        
        Err_RefuseJoin_OffRate      =    18,        //坐下时，被桌上的其他玩家拒绝，原因：断线率
        Err_RefuseJoin_NetSpeed     =    19,        //坐下时，被桌上的其他玩家拒绝，原因：网速
        Err_RefuseJoin_Point        =    20,        //坐下时，被桌上的其他玩家拒绝，原因：积分
        Err_RefuseJoin_PointGap     =    21,        //坐下时，被桌上的其他玩家拒绝，原因：积分差
        Err_RefuseJoin_SameIP       =    22,        //坐下时，被桌上的其他玩家拒绝，原因：相同IP
        Err_StopJoin_OffRate        =    23,        //坐下时，桌上其他玩家不符合条件，原因：断线率
        Err_StopJoin_NetSpeed       =    24,        //坐下时，桌上其他玩家不符合条件，原因：网速
        Err_StopJoin_Point          =    25,        //坐下时，桌上其他玩家不符合条件，原因：积分
        Err_StopJoin_PointGap       =    26,        //坐下时，桌上其他玩家不符合条件，原因：积分差
        Err_StopJoin_SameIP         =    27,        //坐下时，桌上其他玩家不符合条件，原因：相同IP
        
        Err_PlayRefused             =    28,        //玩家传送的游戏动作被拒绝
        Err_InvalidAction           =    29,        //不合法的动作
        Err_PermissionDeny          =    30,        //没有足够的操作权限
        Err_RoomFull                =    31,        //房间已满员
        Err_TableFull               =    32,        //桌已满员
        Err_PlayerNotOnLine         =    33,        //被查询的玩家未上线
        Err_NoFreeTable             =    34,        //无空闲的游戏桌
        Err_TooManyOpenRoom         =    35,        //玩家进入的房间太多
        Err_TooManyOpenGame         =    36,        //玩家打开的游戏过多
        Err_RuleWords               =    37,        //玩家说了不文明的话
        Err_CodeFailed              =    38,        //系统编解码失败
        Err_LockFailed              =    39,        //加锁失败
        Err_UnlockFailed            =    40,        //解锁失败
        Err_ResouceLack             =    41,        //资源不够
        Err_TimeOut                 =    42,        //操作超时
        
        Err_NotAdmin                =    44,        //非系统管理员提交了系统消息命令
        Err_InvalidSysMsg           =    45,        //系统消息的参数错误，如指定UIN发送,又指定是进入房间的系统消息
        Err_InvalidQQClientID       =    46,        //无效的玩家编号
        Err_GetFriendInfo           =    47,        //系统消息的参数错误，如指定UIN发送,又指定是进入房间的系统消息
        Err_Uin                     =    48,        //DB反馈某个Uin的游戏分布不是指定Uin的
        Err_InvalidDlg              =    49,        //请求某个uin的详细信息时，提交的dlg错误
        Err_GetPlayerGameInfo       =    50,
        Err_CannotFindEmptyTable    =    51,        //请求某个uin的详细信息时，提交的dlg错误
        Err_NotTableOwner           =    52,        //请求某个uin的详细信息时，提交的dlg错误
        Err_CanNotCreateChatTable   =    53,        //请求某个uin的详细信息时，提交的dlg错误
        Err_RepeateCreateChatTable  =    54,        //请求某个uin的详细信息时，提交的dlg错误
        Err_CanNotConfigChatTable   =    55,        //请求某个uin的详细信息时，提交的dlg错误
        Err_EnterNotInGameChatTable =    56,
        Err_TooManyUsersOnChatTable =    57,
        Err_SetTooManyUsersOnTable  =    58,
        Err_SetSoFewUsersOnTable    =    59,
        Err_CanNotEnterChatTable    =    60,        //请求某个uin的详细信息时，提交的dlg错误
        Err_CanNotCancelCreateChatTable    =    61,             //请求某个uin的详细信息时，提交的dlg错误
        Err_GetTableInfo            =    62,
        
        // 旁观时可能返回的错误值
        Err_NotInGame               =    63,    //旁观时，桌子没有处于游戏状态
        Err_NoViewer                =    64,    //旁观时，旁观对象不在座位上
        
        Err_InvalidGameType         =    66,    //无效的game type
        Err_InvalidRoomInfo         =    67,    //无效的room info
        
        Err_InBlackList             =    68,
        Err_GetHideUin              =    69,        
        Err_InvalidCCCodeVer        =    70,    //客户端提交的动态检查代码的版本或大厅版本不正确
        Err_InvalidHallStamp        =    71,    //客户端提交的大厅stamp不正确
        Err_CheckHallTimeOut        =    72,    //客户端长时间没有上报验证信息
        Err_ClearIntradayLimitOnly  = 1000,     //目前只能取消当日消费限额，不能设置当日消费额
        Err_ExceedSystemUplimit     = 1001,     //设置的限额已超过系统最高限额，设置失败
        Err_ExceedPlayerUplimit     = 1002,     //当日消费超过玩家设置的最高限额
        Err_RefuseJoin_InBlackList  =   75,     //坐下时，被桌上的其他玩家拒绝，原因：被加入黑名单
        Err_RefuseLogin_LimitedQQNo =   76,     //QQ号段受限不能进入游戏
        Err_AntiBot_Internal        =   77,     //反外挂系统内部错误
        Err_WaitingAssignSeatInDFRomm = 78,     //混战房间等待分配座位
        
        Err_Standup_InGame          = 79,
        Err_SitDown_InGame          = 80,
        Err_Invalid_failed          = 81,       // 验证失败
        Err_GameForbidViewGame      = 82,
        
        
        //好友系统相关
        Err_UnmatchedTableKey       = 17,       //坐到被加锁的桌时，传送的key与本桌的key不匹配
        Err_InvalidTableKey         = 83,       //创建好友桌时，发来了非法的key
        Err_CreateFriendTableError  = 84,       //创建好友桌失败  
        
        //道具商城开发添加相关
        Err_NotSufficientFunds     = 85,       //余额不足
        Err_DeliveryGoodsFailed    = 86,       //保存道具失败（即发货失败）  
        Err_PaymentType            = 87,       //错误的支付类型
        Err_InvalidPurchase        = 88,       //无效的购买单（购买单中含有无效的商品）
        Err_DecutTimeOut           = 89,       //扣款超时
        Err_DeliveryTimeOut        = 90,       //发货超时
        Err_OutOfLimitNumber       = 91,       //超出购买限制
        Err_CommoditExpired        = 92,           //商品已经过期
        
        Err_MT_Register_Account_Exist = 93,
        
        Err_MT_Login_Pass_Wrong = 95,
        Err_MT_Login_Account_Wrong = 96,
        
        Err_MT_Signin_Today_Already = 97
    }

    /// <summary>
    /// Net object type.
    /// 网络中的实体类型.
    /// </summary>
    public class NetObjectType
    {
        public const byte FE_CLIENT = 0;
        public const byte FE_GAMESERVER = 1;
        public const byte FE_ROOM = 2;
        public const byte FE_TABLE     = 3;
        public const byte FE_PLAYER = 4;
        public const byte FE_GAMEDB = 5;
        public const byte FE_GAMEROOMMNG = 6;
        public const byte FE_INTERSERVER = 7;
        public const byte FE_STATSVR = 8;
        public const byte FE_LOGSVR = 9;
        public const byte FE_ADMINSVR = 10;
        public const byte FE_PROPERTYINFO = 11;
        public const byte FE_QUERYSVR  = 12;
        public const byte FE_FRIENDSVR = 13;
        public const byte FE_WEBSVR = 14;
        public const byte FE_SHOPSVR = 15;
    }
}

