// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections.Generic;

namespace XUtility
{
    /// <summary>
    /// Resource wraper.
    /// </summary>
    public class ResourceWraper
    {
        private static Dictionary<string, Object> assets = new Dictionary<string, Object>();
        
        /// <summary>
        /// Load the specified path.
        /// </summary>
        /// <param name="path">Path.</param>
        static public Object Load(string path)
        {
            if (string.IsNullOrEmpty(path))
                return null;
            return Resources.Load(path);
        }
        
        /// <summary>
        /// Load the specified path.
        /// </summary>
        /// <param name="path">Path.</param>
        /// <typeparam name="T">The 1st type parameter.</typeparam>
        static public T Load<T>(string path) where T : Object
        {
            if (string.IsNullOrEmpty(path))
                return default(T);
            if (assets.ContainsKey(path))
                return assets [path] as T;
            T t = Resources.Load<T>(path);
            
            assets.Add(path, t);
            
            return t;
        }
        
        /// <summary>
        /// Unloads the asset.
        /// </summary>
        /// <param name="path">Path.</param>
        static public void UnloadAsset(string path)
        {
            if (string.IsNullOrEmpty(path))
                return;
            
            if (assets.ContainsKey(path))
            {
                Object o = assets[path];
                assets.Remove(path);
                if( o == null)
                    return;
                Resources.UnloadAsset(o);
            }
        }
        
        /// <summary>
        /// Loads the effect.
        /// </summary>
        /// <returns>The effect.</returns>
        /// <param name="name">Name.</param>
        /// <param name="parent">Parent.</param>
        /// <param name="fixedPoint">Fixed point.</param>
        static public GameObject LoadEffect(string name, Transform parent, string fixedPoint)
        {
            if (string.IsNullOrEmpty(name))
                return null;
            
            GameObject re = Load<GameObject>(name);
            
            if (re == null)
                return null;
            
            GameObject go = GameObject.Instantiate(re) as GameObject;
            
            if (parent != null)
            {
                Transform t = parent.transform;
                
                if(!string.IsNullOrEmpty(fixedPoint))
                {
                    t = Helper.FindChild(parent, fixedPoint,true);
                }
                Helper.Fixto(go.transform,t ,true);
            }
            
            return go;
        }
        
        /// <summary>
        /// Loads the text.
        /// </summary>
        /// <returns>The text.</returns>
        /// <param name="path">Path.</param>
        static public string LoadText(string path)
        {
            TextAsset text = Load<TextAsset>(path);
            
            if (text != null)
                return text.text;
            
            return "";
        }
        
        /// <summary>
        /// Registers the loaded NP.
        /// </summary>
        /// <param name="fun">Fun.</param>
        static public void RegisterLoadedNPC(CustomerAction<int,GameObject> fun)
        {
            if (fun == null)
                return;
            if (LoadedNPC == null)
                LoadedNPC = fun;
            else
                LoadedNPC += fun;
        }
        
        /// <summary>
        /// Subregisters the loaded NP.
        /// </summary>
        /// <param name="fun">Fun.</param>
        static public void subregisterLoadedNPC(CustomerAction<int,GameObject> fun)
        {
            if (fun == null)
                return;
            if (LoadedNPC == null)
                return;
            else
                LoadedNPC -= fun;
        }
        
        
        /// <summary>
        /// The loaded NP.
        /// </summary>
        static private CustomerAction<int,GameObject> LoadedNPC;
        
        /// <summary>
        /// Loads the NP.
        /// 酷跑中的NPC.
        /// </summary>
        /// <returns>The NP.</returns>
        /// <param name="id">Identifier.</param>
        static public GameObject LoadNPC(int id)
        {
            GameObject go = Load<GameObject>("Player/RunNPC");
            if (go != null)
            {
                go = GameObject.Instantiate(go) as GameObject;
                if(LoadedNPC != null)
                    LoadedNPC(id,go);
                return go;
            }
            return null;
        }
        
        /// <summary>
        /// Loads the model.
        /// </summary>
        /// <returns>The model.</returns>
        /// <param name="id">Identifier.</param>
        static public GameObject LoadModel(int id)
        {
          return null;
        }
        
        /// <summary>
        /// Registers the loaded symbol.
        /// </summary>
        /// <param name="fun">Fun.</param>
        static public void RegisterLoadedSymbol(CustomerAction<int,int,GameObject> fun)
        {
            if (fun == null)
                return;
            if (LoadedSysbol == null)
                LoadedSysbol = fun;
            else
                LoadedSysbol += fun;
        }
        
        /// <summary>
        /// Subregisters the loaded symbol.
        /// </summary>
        /// <param name="fun">Fun.</param>
        static public void subregisterLoadedSymbol(CustomerAction<int,int,GameObject> fun)
        {
            if (fun == null)
                return;
            if (LoadedSysbol == null)
                return;
            else
                LoadedSysbol -= fun;
        }
        
        /// <summary>
        /// The loaded sysbol.
        /// </summary>
        static private CustomerAction<int,int,GameObject> LoadedSysbol;
        
        /// <summary>
        /// Loads the sysbol.
        /// </summary>
        /// <returns>The sysbol.</returns>
        /// <param name="id">Identifier.</param>
        /// <param name="level">Level.</param>
        static public GameObject LoadSysbol(int id, int level)
        {
          
            return null;
        }
    }
}

