// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace XUtility
{
    /// <summary>
    /// Global message router.
    /// </summary>
    public class GlobalMessageRouter : MessageRouter<String>
    {
        /// <summary>
        /// Gets the instance.
        /// </summary>
        /// <value>The instance.</value>
        public static GlobalMessageRouter Instance
        {
            get{return instance;}
        }

        private static GlobalMessageRouter instance;

        static GlobalMessageRouter()
        {
            instance = new GlobalMessageRouter();
        }
    }
}

