// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Net.Sockets;
using System.Collections.Generic;
using XUtility;

namespace XSocketClient
{
    /// <summary>
    /// Network facade.
    /// Contect,Discontct,SendEvent, SendRequest, HandleEvent, HandelReponse, HandleState.
    /// RegisterType
    /// </summary>
    public class NetworkFacade
    {

        /// <summary>
        /// Gets the instance.
        /// </summary>
        /// <value>The instance.</value>
        public static NetworkFacade Instance{get {return Instance;}}

        /// <summary>
        /// Gets a value indicating whether this <see cref="XSocketClient.NetworkFacade"/> is connected.
        /// </summary>
        /// <value><c>true</c> if connected; otherwise, <c>false</c>.</value>
        public static bool Connected
        {
            get{return instance.tcp.Connected;}
        }

        private static NetworkFacade instance;

        private TCPWraper tcp;

        #region all send API

        /// <summary>
        /// Contect the specified ip and port.
        /// </summary>
        /// <param name="ip">Ip.</param>
        /// <param name="port">Port.</param>
        public static bool Contect(string ip, int port)
        {
            if(Connected)
                DisConnect();
            return instance.tcp.Connect(ip, port);
        }

        /// <summary>
        /// Dises the connect.
        /// </summary>
        public static void DisConnect()
        {
            if(Connected)
                instance.tcp.Disconnect();
        }

        /// <summary>
        /// Register the specified name and pwd.
        /// </summary>
        /// <param name="name">Name.</param>
        /// <param name="pwd">Pwd.</param>
        public static bool Register(string name, string pwd)
        {
            if (!Connected)
                return false;
            
            if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(pwd))
                return false;
            
            instance.tcp.SendRequest(new Register(name, pwd));return true;
        }

        /// <summary>
        /// Login the specified name and pwd.
        /// </summary>
        /// <param name="name">Name.</param>
        /// <param name="pwd">Pwd.</param>
        public static bool Login(string name, string pwd)
        {
            if (!Connected)
                return false;

            if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(pwd))
                return false;

            instance.tcp.SendRequest(new Login(name, pwd));
            return true;
        }

        /// <summary>
        /// Gets the room.
        /// </summary>
        public static void GetRoom()
        {
            if (!Connected)
                return;
            instance.tcp.SendRequest(new RoomInfo());
        }


        public static void LoginRoom()
        {
            if (TCPWraper.Ip != Session.ServerIP || TCPWraper.Port != Session.ServerPort)
            {
                DisConnect();// disconnect from login.
                Contect(Session.ServerIP, Session.ServerPort); // connect to gameSrv.
            }
            //block when connect.
            if (Connected)
                instance.tcp.SendRequest(new LoginRoomVo());
        }

        /// <summary>
        /// Enters the room.
        /// </summary>
        public static void EnterRoom()
        {
            if (Connected)
                instance.tcp.SendRequest(new EnterRoomVO());
        }

        /// <summary>
        /// Leaves the room.
        /// </summary>
        public static void LeaveRoom()
        {
            if (Connected)
                instance.tcp.SendRequest(new LeaveRoomVO());
        }

       /// <summary>
       /// Sits down.
       /// </summary>
       /// <param name="tableId">Table identifier.</param>
       /// <param name="seatId">Seat identifier.</param>
        public static void SitDown(int tableId, int seatId)
        {
            if (Connected)
                instance.tcp.SendRequest(new SitDownVO(tableId,seatId){});
        }

        /// <summary>
        /// Standup this instance.
        /// </summary>
        public static void Standup()
        {
            if(Connected)
                instance.tcp.SendRequest(new StandupVO());
        }

        /// <summary>
        /// Play this instance.
        /// </summary>
        public static void Play()
        {
            if (Connected)
                instance.tcp.SendRequest(new GamePlay());
        }

        #endregion

        #region subscribe handle

        /// <summary>
        /// Subscribes the response.
        /// </summary>
        /// <param name="callback">Callback.</param>
        public static void SubscribeResponse(CustomerAction<int,Int16, byte[]> callback)
        {
            if(callback != null)
                instance.tcp.RegisterResponse(callback);
        }

        /// <summary>
        /// Subscribes the connect status.
        /// </summary>
        /// <param name="status">Status.</param>
        public static void SubscribeConnectStatus(CustomerAction<bool> status)
        {
            if (status != null)
                instance.tcp.RegisterConnectStatus(status);
        }

       /// <summary>
       /// Subscribes the event.
       /// </summary>
       /// <param name="eventHandle">Event handle.</param>
        public static void SubscribeEvent(CustomerAction<Int16, byte[]> eventHandle)
        {
            if(eventHandle != null)
                instance.tcp.RegisterEvent(eventHandle);
        }
        #endregion

        /// <summary>
        /// Update this instance.
        /// </summary>
        public static void Update()
        {
            instance.tcp.Update();
        }

        static NetworkFacade()
        {
            instance = new NetworkFacade();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="XSocketClient.NetworkFacade"/> class.
        /// </summary>
        protected NetworkFacade()
        {
            tcp = new TCPWraper();
        }
    }
}

