// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using PureMVC.Patterns;
using PureMVC.Interfaces;
using XUtility;

namespace XMVC
{
    /// <summary>
    /// Start command.
    /// </summary>
    public class StartCommand:Notifier, ICommand, INotifier
    {
        private delegate bool LoadConfingDelegate(string content);

        private Dictionary<string, LoadConfingDelegate> delegates;

        private Dictionary<string, LoadConfingDelegate>.Enumerator enumerator;

        /// <summary>
        /// Execute the specified notification.
        /// </summary>
        /// <param name="notification">Notification.</param>
        public void Execute(PureMVC.Interfaces.INotification notification)
        {

            delegates = new Dictionary<string, LoadConfingDelegate>(){
                /*{"Config/Skill",DBFacade.Instance.LoadSkill},*/
            };

            CustomerUpdate.Instance.AddUpdate(LoadConfig);
            enumerator = delegates.GetEnumerator();
            GlobalLog.Log("StartCommand Succed");
        }

        private bool nullRun;

        private void LoadConfig()
        {
            if(nullRun)
            {
                nullRun = false;
                return;
            }

            if (enumerator.MoveNext())
            {
                string content = ResourceWraper.LoadText(enumerator.Current.Key);
                if (string.IsNullOrEmpty(content))
                    return;
                try
                {
                    enumerator.Current.Value(content);
                }
                catch(System.Exception e)
                {
                    GlobalLog.LogError(enumerator.Current.Key + " Error " + e.Message);
                }
            }
            else
                CustomerUpdate.Instance.RemoveUpdate(LoadConfig);
        }
    }
}

